### ISSUE TITLE
Is this an A87 form factor?

### ISSUE THREAD

**Issue by dhanakane** [Gondolindrim/Apollo87H#2]
I’m hoping to use this as a drop in replacement for an H87c. Would it be suitable for this?

**Comment by Gondolindrim** [comment]
Hello,

It was designed to be a replacement to H87/A87 PCBs. Please note that the compatibility list is still limited and I cannot guarantee fitness for a particular product (please read the license).

**Comment by dhanakane** [comment]
Thank you. If you’ve got any tips on how to check for theoretical fit then that would be much appreciated. I’m assuming I can open up the PCB file in something like FreeCAD and look at the dimensions?

If the PCB footprint is the same as an H87, then it should work for my use case. Obviously, I understand this is all at my own risk.

Thanks for putting this project out there. I really appreciate the work!

**Comment by Gondolindrim** [comment]
Confirmedly fits F1-84 by Geonworks

**Comment by Gondolindrim** [comment]
> Thank you. If you’ve got any tips on how to check for theoretical fit then that would be much appreciated. I’m assuming I can open up the PCB file in something like FreeCAD and look at the dimensions?

> If the PCB footprint is the same as an H87, then it should work for my use case. Obviously, I understand this is all at my own risk.

> Thanks for putting this project out there. I really appreciate the work!

No problem!

There will be STEP files released soon, I just haven't had time to look at the weird error some of the LED footprints are giving me. If you have a 3D model of your case you should be able to test with the STEP if the PCB fits.

**Comment by dhanakane** [comment]
Unfortunately I'm just a consumer and not a case designer. I'd be willing to order a prototype if the files to do so (gerber?) are made available, at my own risk obviously :)

**Comment by Gondolindrim** [comment]
Prototypes for Apollo87H were already ordered -- however, I'll stil take your offer. If you'd like to help the project, you could order protos for Athena (solderable version of Apollo).

**Comment by dhanakane** [comment]
Happy to do so if you can point me at the repo and files?

**Comment by Gondolindrim** [comment]
Athena is mid-development and I plan to release it by the end of the month.

**Comment by Gondolindrim** [comment]
Closing this as prototypes were ordered and this PCB and Athena are confirmed H87 replacements.
